image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -hodor123 -p<qq89427157>

build:
  stage: build
  script:
    - docker build -t "wechat/test:3.3" .
    - docker push wechat/test:3.3
  only:
    - master
  tags:
    - docker
